version: '2'
services:
  rabbitmq:
    image: rabbitmq
  web:
    ports:
      - "80:8000"
    image: asia.gcr.io/prog-edu-assistant/server
    entrypoint: ['/usr/local/bin/uploadserver', '-upload_dir', '/tmp', '-logtostderr', '-v', '3', '-queue_spec', 'amqp://guest:guest@rabbitmq:5672/', '-allow_cors_origin', 'http://localhost:8888', '-use_openid']
    env_file:
      # ./secret.env should define the following variables
      # Note 1: values should not use quotes.
      # Note 2: keep the content of the file secret!
      #CLIENT_ID=<an OAuth2 client ID obtained from the Open ID Connect provider>
      #CLIENT_SECRET=<an OAuth2 client secret obtained from the Open ID Connect provider>
      #COOKIE_AUTH_KEY=<random string of 16 characters>
      #COOKIE_ENCRYPT_KEY=<random string of 16 or 32 characters>
      #SERVER_URL=<the public URL of the server with port but without ending slash>
      - secret.env
    read_only: true
    tmpfs: /tmp
  worker:
    image: asia.gcr.io/prog-edu-assistant/worker
    entrypoint: ['/usr/local/bin/worker', '-scratch_dir', '/tmp', '-autograder_dir', '/autograder', '-logtostderr', '-v', '5', '-queue_spec', 'amqp://guest:guest@rabbitmq:5672/', '-python_path', '/usr/bin/python', '-disable_cleanup', '-auto_remove']
    tmpfs: /tmp
    read_only: true
